### ISSUE TITLE
Error using `telefphone-line-defsegment*` macro

### ISSUE THREAD

**Issue by squiter** [dbordak/telephone-line#43]
Hello guys, after update telephone-line I started to get the `Not enough arguments for format string` error, but I'm not sure if this was caused by the update or because of my customizations. I have a lot of customizations that use `telephone-line-defsegment`'s macro but the only one that is raising the error is the that:

```emacs-lisp
(telephone-line-defsegment* squiter/telephone-line-projectile-project-name
  `(""
    ,(telephone-line-raw (ignore-errors (format "📁 %s" (projectile-project-name))))))
```

I already run the body of the macro alone and it doesn't raise error.

Can you help me to find the error?

**Comment by dbordak** [comment]
Ah, sorry about this, I updated the defsegment format to resemble defun (needed to do this to add support for args; soon you'll be able to specify how much padding the position segment uses, etc).

So, this would become

``` emacs-lisp
(telephone-line-defsegment* squiter/telephone-line-projectile-project-name ()
  `(""
    ,(telephone-line-raw (ignore-errors (format "📁 %s" (projectile-project-name))))))
```

However, unless I'm mistaken, I think you can just do

``` emacs-lisp
(telephone-line-defsegment* squiter/telephone-line-projectile-project-name ()
  (ignore-errors (format "📁 %s" (projectile-project-name))))
```

or even

``` emacs-lisp
(telephone-line-defsegment* squiter/telephone-line-projectile-project-name ()
  `("📁 " ,(projectile-project-name)))
```

Since that whole list-starting-with-a-string form is just for concatenation anyway.

You don't need telephone-line-raw since that's for either trimming (which you don't need) or hiding empty segments (and the way you defined this, it can never be an empty string).

**Comment by squiter** [comment]
Wow @dbordak awesome! It works perfectly! Thanky you so much :+1:
