### ISSUE TITLE
reloading

### ISSUE THREAD

**Issue by BrianHicks** [dbordak/telephone-line#51]
hey there. I'm just starting out with customizing my modeline and having to restart emacs every time. I've heard that's bad. Is there a way I can try out different configurations of telephone-line without restarting the whole editor?

**Comment by dbordak** [comment]
You can customize telephone-line while running (you can use `customize` or just set values in `ielm` if you know what you're doing, or if you want to test your config as it is you can reload it), however because of the way telephone-line precompiles its configuration, your changes will only apply to new buffers.

**Comment by BrianHicks** [comment]
> your changes will only apply to new buffers.

this was the tip I needed, thank you! 😄
