### ISSUE TITLE
Nothing displayed in the modline in terminal emacs

### ISSUE THREAD

**Issue by yilkalargaw** [dbordak/telephone-line#57]
When I am using emacs in terminal there is nothing displayed in the modeline. My init file configs concerning telephone are as follows

`    
(use-package telephone-line
     :ensure t
     :defer 1
      :init 
	          (setq telephone-line-primary-left-separator 'telephone-line-cubed-left
			  telephone-line-secondary-left-separator 'telephone-line-cubed-hollow-left
			  telephone-line-primary-right-separator 'telephone-line-cubed-left
			  telephone-line-secondary-right-separator 'telephone-line-cubed-hollow-left)
			  (setq telephone-line-subseparator-faces '())
			  (setq telephone-line-height 24)
      :config (telephone-line-mode 1)
)

`
So my question is do I need to run telephone line for graphical emacs only or does it work for the terminal too. If it works for the terminal what am I doing wrong. It is because I am a novice at elisp that I can't figure it out from the code. 

By the way the telephone-line is the best modline package by miles.

**Comment by dbordak** [comment]
No, the terminal *is* supported, it's just not working correctly here.

So, the reason for this is (I believe, I haven't tested it yet) that the separators you're using don't have a terminal backup set. I probably shouldn't have tied the two together... Anyway, try not setting the separators in your config. If it continues to render nothing at all, then the issue is somewhere else. If it renders everything but the separators, then it's a font issue. If it works fine, then it's what I said above.

**Comment by yilkalargaw** [comment]
Thanks @dbordak,  you were right it was the separators. I just added (if (display-graphic-p)) and it worked fine. If you can you should correct it and mark it for enahncment . I would like to help but my elisp is crappy. thanks

**Comment by dbordak** [comment]
Yeah, I do want to fix this, just not sure how I should do it. Have a backup setting, if the separator doesn't have anything set? Set the two types of separators separately? etc.
