### ISSUE TITLE
Option to disable telephone-line mouse menu/tooltip in segments

### ISSUE THREAD

**Issue by ogdenwebb** [dbordak/telephone-line#77]
I'm using Emacs only via keyboard, so help-echo messages just bores me. I guess this part of telephone-line should be optional.

**Comment by dbordak** [comment]
This would be a lot of work for not a lot of gain. I guess you could re-propertize everything at the end to clear out properties, but even so. They're consuming an insignificant amount of RAM, and don't appear unless you _do_ mouse over them.

Just ignore them ;)

**Comment by dbordak** [comment]
Just to wrap this up: mouse menu is an emacs feature, telephone-line just defines the markup that allows emacs to render it. Largely, this is because I copy built-in mode-line blobs directly (which makes for a lot less code on my end :) ). 

I didn't know about that setting, but I'm glad to see you found a solution.
